In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
!pip install openpyxl

  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)



[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
df = pd.read_excel('insurance_data.csv', engine='openpyxl')

In [7]:
df.head()

age  affordability  insurance
0   21           0.22          0
1   58           0.82          1
2   47           0.99          1
3   24           0.30          0
4   53           0.83          1

In [9]:
!pip install scikit-learn

  Using cached scikit_learn-1.6.1-cp312-cp312-win_amd64.whl.metadata (15 kB)
  Using cached scipy-1.15.2-cp312-cp312-win_amd64.whl.metadata (60 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.6.1-cp312-cp312-win_amd64.whl (11.1 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached scipy-1.15.2-cp312-cp312-win_amd64.whl (40.9 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)



[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df[['age', 'affordability']], df.insurance, test_size=0.2, random_state=42)

In [11]:
len(x_train)

22

In [12]:
df.shape

(28, 3)

In [13]:
x_train_scaled = x_train.copy()
x_train_scaled['age'] = x_train_scaled['age'] / 100
x_test_scaled = x_test.copy()
x_test_scaled['age'] = x_test_scaled['age'] / 100

In [14]:
x_train_scaled

age  affordability
17  0.18           0.71
22  0.45           0.22
11  0.28           0.92
13  0.59           0.90
15  0.46           0.65
1   0.58           0.82
4   0.53           0.83
5   0.36           0.65
2   0.47           0.99
16  0.58           0.17
23  0.50           0.99
3   0.24           0.30
26  0.52           0.84
24  0.49           0.93
18  0.55           0.28
27  0.50           0.71
20  0.19           0.41
7   0.56           0.81
10  0.50           0.13
14  0.53           0.90
19  0.33           0.36
6   0.23           0.45

In [15]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.fit(x_train_scaled, y_train, epochs=5000)

c:\Users\avinash\Downloads\my projects\Deep learning\tf-env\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.6364 - loss: 0.5503
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.6364 - loss: 0.5501
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.6364 - loss: 0.5499
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6364 - loss: 0.5497
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 0.6364 - loss: 0.5496
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.6364 - loss: 0.5494
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.6364 - loss: 0.5492
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.6364 - loss: 0.5490
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.6364 - loss: 0.5489
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.6364 - loss: 0.5487
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6364 - loss: 0.5485
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accura

In [16]:
model.evaluate(x_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step - accuracy: 0.8333 - loss: 0.3554


[0.3553571403026581, 0.8333333134651184]

In [18]:
x_test_scaled

age  affordability
9   0.60           0.88
25  0.45           0.55
8   0.45           0.58
21  0.19           0.36
0   0.21           0.22
12  0.43           0.46

In [17]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step


array([[0.9327296 ],
       [0.6189414 ],
       [0.65789425],
       [0.25321165],
       [0.13807623],
       [0.4850587 ]], dtype=float32)

In [19]:
y_test

9     1
25    1
8     1
21    0
0     0
12    1
Name: insurance, dtype: int64

In [20]:
coef, intercept = model.get_weights()

In [21]:
coef, intercept

(array([[1.9120181],
        [5.628892 ]], dtype=float32),
 array([-3.471241], dtype=float32))

NEURAL NETWORKS WITHOUT TENSORFLOW

In [22]:
def sigmoid(x):
    import math
    return 1 / (1 + math.exp( -x))

In [23]:
sigmoid(18)

0.9999999847700205

In [24]:
def prediction(age, affordability):
   W_sum =  coef[0]* age + coef[1] * affordability + intercept
   return sigmoid(W_sum)

In [25]:
prediction(0.60, 0.88)

C:\Users\avinash\AppData\Local\Temp\ipykernel_18208\4183141362.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp( -x))


0.932729569154936

In [26]:
prediction(0.45, 0.55)

C:\Users\avinash\AppData\Local\Temp\ipykernel_18208\4183141362.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp( -x))


0.6189414382278721

GRADIENT DESCENT ALGORITHM

In [27]:
def log_loss(y_true, y_prediction):
    epsilon = 1e-15
    y_prediction_new = [max(i, epsilon) for i in y_prediction]
    y_prediction_new = [min(i, 1-epsilon) for i in y_prediction_new]
    y_prediction_new = np.array(y_prediction_new)
    return -np.mean(y_true * np.log(y_prediction_new) + (1-y_true) * np.log(1-y_prediction_new))

In [28]:
def sig_num(x):
    return 1 / (1+np.exp(-x))
sig_num(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [33]:
def gradient(age, affordability, y_true, epochs, loss_threashold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)

    for i in range(epochs):
        sum =  w1 * age + w2 * affordability + bias
        y_pred = sig_num(sum)
        loss = log_loss(y_true, y_pred)
        wd = (1/n)*np.dot(np.transpose(age),  (y_pred - y_true))
        wd2 = (1/n)*np.dot(np.transpose(affordability),  (y_pred - y_true))
        bias_d = np.mean(y_pred - y_true)
        w1 = w1 - rate * wd
        w2 = w2 - rate * wd2

        bias = bias - rate * bias_d

        print(f"Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}")
        if loss <= loss_threashold:
            break
    return w1, w2, bias

In [34]:
gradient(x_train_scaled['age'], x_train_scaled['affordability'], y_train, 1000, 0.2007)

Epoch:0, w1:0.9846375367293332, w2:1.021371134042702, bias:-0.051740367136018345, loss:0.5502667196847322
Epoch:1, w1:0.9711312561617479, w2:1.045159623360032, bias:-0.0991465791771908, loss:0.5437275809230068
Epoch:2, w1:0.9592409636199624, w2:1.0710143365613904, bias:-0.1427758577789185, loss:0.5378875865362281
Epoch:3, w1:0.9487486902253743, w2:1.0986167929609783, bias:-0.18313273940961772, loss:0.5325748347200223
Epoch:4, w1:0.9394598765330383, w2:1.1276829382544038, bias:-0.22066680301999442, loss:0.52765951036244
Epoch:5, w1:0.9312031270132335, w2:1.1579628079167374, bias:-0.25577358613218787, loss:0.5230449753282032
Epoch:6, w1:0.923829030710659, w2:1.189238806528438, bias:-0.28879755999282675, loss:0.5186601018782009
Epoch:7, w1:0.9172084333711561, w2:1.2213231714652926, bias:-0.32003629278113693, loss:0.5144529970182127
Epoch:8, w1:0.9112304423799401, w2:1.254055037194283, bias:-0.34974516968418967, loss:0.510386047281929
Epoch:9, w1:0.9058003584870852, w2:1.287297387843688, b

(np.float64(0.8099870452155),
 np.float64(5.852459939778899),
 np.float64(-3.108871068375992))

In [35]:
coef, intercept

(array([[1.9120181],
        [5.628892 ]], dtype=float32),
 array([-3.471241], dtype=float32))

In [50]:
class myNN:
    def __init__(self):
        self.w1=  1
        self.w2 = 1
        self.bias = 0
    def fit(self, x, y, epochs, loss_threashold):
        self.w1, self.w2, self.bias = self.gradient(x['age'], x['affordability'], y, epochs, loss_threashold)
    def predict(self, x_test):
        w_s = self.w1 * x_test['age'] + self.w2 * x_test['affordability'] + self.bias
        return sig_num(w_s)
    def gradient(self, age, affordability, y_true, epochs, loss_threashold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)

        for i in range(epochs):
            sum = w1 * age + w2 * affordability + bias
            y_pred = sig_num(sum)
            loss = log_loss(y_true, y_pred)
            wd = (1/n) * np.dot(np.transpose(age), (y_pred - y_true))
            wd2 = (1/n) * np.dot(np.transpose(affordability), (y_pred - y_true))
            bias_d = np.mean(y_pred - y_true)
            w1 = w1 - rate * wd
            w2 = w2 - rate * wd2
            bias = bias - rate * bias_d
            if i % 50 == 0:
                print(f"Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}")
            if loss <= loss_threashold:
                 print(f"Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}")
                 break
                

        return w1, w2, bias


In [51]:
custom = myNN()
custom.fit(x_train_scaled, y_train, epochs=500, loss_threashold=0.2007)

Epoch:0, w1:0.9846375367293332, w2:1.021371134042702, bias:-0.051740367136018345, loss:0.5502667196847322
Epoch:50, w1:0.8104488838539625, w2:2.610618467863258, bias:-1.2093017036549984, loss:0.3847949814847862
Epoch:100, w1:0.7744995114121784, w2:3.880277895293155, bias:-1.9531844487026584, loss:0.296905196436202
Epoch:150, w1:0.778009130207473, w2:4.877098204832312, bias:-2.535959226569609, loss:0.243000050051793
Epoch:200, w1:0.8027483958777636, w2:5.691745876940848, bias:-3.0141977854201816, loss:0.20698345590891823
Epoch:211, w1:0.8099870452155, w2:5.852459939778899, bias:-3.108871068375992, loss:0.20061619814162113


In [52]:
coef, intercept

(array([[1.9120181],
        [5.628892 ]], dtype=float32),
 array([-3.471241], dtype=float32))

In [53]:
custom.predict(x_test_scaled)

9     0.926033
25    0.616443
8     0.657022
21    0.299834
0     0.160942
12    0.482895
dtype: float64

In [54]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 406ms/step


array([[0.9327296 ],
       [0.6189414 ],
       [0.65789425],
       [0.25321165],
       [0.13807623],
       [0.4850587 ]], dtype=float32)