Loss functions

In [2]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error
y_true_reg = np.array([3.0, -0.5, 2.0, 7.0])
y_pred_red = np.array([2.5, 0.0, 2.1, 7.8])

In [3]:
y_true_bin = np.array([1,0,1,1])
y_pred_bin = np.array([0.9, 0.2, 0.7, 0.8])

In [4]:
y_true_multi = np.array([[1,0,0], [0,1,0], [0,0,1]])
y_pred_multi = np.array([[0.8, 0.1, 0.1], [0.2, 0.7, 0.1], [0.1, 0.2, 0.7]])

In [5]:
print(y_true_multi)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
loss = mean_squared_error(y_true_reg, y_pred_red)
print("mean squared error:", loss)

mean squared error: 0.2874999999999999


In [7]:
MAE=  mean_absolute_error(y_true_reg, y_pred_red)
print('Mean absolute error:', MAE)

Mean absolute error: 0.475


In [9]:
def binary(y_true, y_pred):
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))
print("binary cross entropy loss:", binary(y_true_bin, y_pred_bin))


binary cross entropy loss: 0.22708064055624455


In [10]:
def category_cross(y_true, y_pred):
    return -np.mean(np.sum(y_true * np.log(y_pred), axis=1))
print('categorical loss:', category_cross(y_true_multi, y_pred_multi))

categorical loss: 0.3121644797305582


In [11]:
def  huber(a, b, delta = 1.0):
    error = a - b
    return np.mean(np.where(np.abs(error) <= delta, 0.5 * error **2, delta * (np.abs(error) - 0.5 * delta)))
print('huber loss:', huber(y_true_reg, y_pred_red))

huber loss: 0.14374999999999996
